[workspace]
resolver = "2"
members = [
    "stellar_insights",
    "multisig",
    "upgrade",
    "upgrade/test_contracts/stellar_insights_legacy",
    "upgrade/test_contracts/stellar_insights_v2",
    "time-locked-transactions",
]

[workspace.dependencies]
soroban-sdk = "27.0.6"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
